// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetSqlDataDicV2.Web.Data;

#nullable disable

namespace NetSqlDataDicV2.Web.Migrations
{
    [DbContext(typeof(DataDictionaryDbContext))]
    partial class DataDictionaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetSqlDataDicV2.Web.Models.Entities.DataElement", b =>
                {
                    b.Property<int>("DataElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataElementId"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataElementName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DataElementType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DataPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DatabaseServer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignKeyTo")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalDataSource")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("Precision")
                        .HasColumnType("int");

                    b.Property<long?>("RowCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("Scale")
                        .HasColumnType("int");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("dbo");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("DataElementId");

                    b.HasIndex("DatabaseServer", "DatabaseName", "SchemaName", "TableName")
                        .HasDatabaseName("IX_DataElements_Table")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("DatabaseServer", "DatabaseName", "SchemaName", "TableName", "ColumnName")
                        .IsUnique()
                        .HasDatabaseName("UQ_DataElements_Location")
                        .HasFilter("[ColumnName] IS NOT NULL");

                    b.ToTable("DataElements", (string)null);
                });

            modelBuilder.Entity("NetSqlDataDicV2.Web.Models.Entities.SourceConnection", b =>
                {
                    b.Property<int>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectionId"));

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DatabaseServer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ConnectionId");

                    b.ToTable("SourceConnections", (string)null);
                });

            modelBuilder.Entity("NetSqlDataDicV2.Web.Models.Entities.SyncHistory", b =>
                {
                    b.Property<int>("SyncHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SyncHistoryId"));

                    b.Property<int?>("ColumnsAdded")
                        .HasColumnType("int");

                    b.Property<int?>("ColumnsProcessed")
                        .HasColumnType("int");

                    b.Property<int?>("ColumnsRemoved")
                        .HasColumnType("int");

                    b.Property<int?>("ColumnsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DatabaseServer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SyncEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TablesProcessed")
                        .HasColumnType("int");

                    b.HasKey("SyncHistoryId");

                    b.ToTable("SyncHistory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
